services:
  youtub34:
    image: jonmaddox/youtub3r:${TAG:-latest}
    container_name: youtub3r
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - VIDEO_PATH=${VIDEO_PATH:-/youtube}
    volumes:
      - ${VIDEOS_SHARE}:${VIDEO_PATH:-/youtube}
